"""empty message

Revision ID: 589d846f900c
Revises: c6d7ca816786
Create Date: 2017-02-05 00:28:27.159062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '589d846f900c'
down_revision = 'c6d7ca816786'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # Alter column not supported in Sqlite
    print "creating machine table..."
    op.create_table('machine',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True, server_default=sa.func.current_timestamp()),
    sa.Column('updated_at', sa.DateTime(), nullable=True, server_default=sa.func.current_timestamp()),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False, server_default='Available'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    print "dropping machine table..."
    op.drop_table('machine')
    ### end Alembic commands ###

