"""empty message

Revision ID: d8ad39de81b3
Revises: 
Create Date: 2016-11-21 17:03:39.319499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ad39de81b3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('color',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('supported_mold_type', sa.Integer(), nullable=True),
    sa.Column('installed_mold_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('downtime_start', sa.Date(), nullable=True),
    sa.Column('downtime_end', sa.Date(), nullable=True),
    sa.Column('total_downtime', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('modified_at', sa.Date(), nullable=True),
    sa.Column('supervisor_attention', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_mold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mold_type', sa.String(), nullable=True),
    sa.Column('time_to_install', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('modified_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('machine_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('work_in_progress', sa.String(), nullable=True),
    sa.Column('slot_1', sa.Integer(), nullable=True),
    sa.Column('slot_2', sa.Integer(), nullable=True),
    sa.Column('slot_3', sa.Integer(), nullable=True),
    sa.Column('slot_4', sa.Integer(), nullable=True),
    sa.Column('slot_5', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', ' IN_PROGRESS', ' COMPLETED', ' SHIPPED'), nullable=True),
    sa.Column('shift_name', sa.String(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.Column('raw_material_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('team_lead_id', sa.Integer(), nullable=True),
    sa.Column('team_lead_name', sa.String(), nullable=True),
    sa.Column('estimated_time_to_finish', sa.Integer(), nullable=True),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('delay', sa.Integer(), nullable=True),
    sa.Column('delay_reason', sa.String(), nullable=True),
    sa.Column('planned_quantity', sa.Integer(), nullable=True),
    sa.Column('finished_quantity', sa.Integer(), nullable=True),
    sa.Column('defected_quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('shift_name', sa.String(), nullable=True),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=True),
    sa.Column('total_working_hours', sa.Integer(), nullable=True),
    sa.Column('assigned_machine', sa.Integer(), nullable=True),
    sa.Column('sign_in_at', sa.Date(), nullable=True),
    sa.Column('sign_out_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shift_name', sa.String(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=True),
    sa.Column('end_time', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('salary', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('IN', 'OUT', 'SICK', 'VACATION'), nullable=True),
    sa.Column('shift_name', sa.Enum('Morning', 'Evening', 'Night'), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('profile_photo_url', sa.String(), nullable=True),
    sa.Column('last_login_at', sa.Date(), nullable=True),
    sa.Column('modified_at', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('M', 'F'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'SHIPPED'), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('raw_material_quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.Column('estimated_time_to_finish', sa.Integer(), nullable=True),
    sa.Column('production_start_at', sa.Date(), nullable=True),
    sa.Column('production_end_at', sa.Date(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('time_to_build', sa.Integer(), nullable=True),
    sa.Column('selling_price', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('num_employee_required', sa.Integer(), nullable=True),
    sa.Column('mold_id', sa.Integer(), nullable=True),
    sa.Column('raw_material_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['raw_material_id'], ['raw_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('order')
    op.drop_table('user')
    op.drop_table('shift')
    op.drop_table('schedule')
    op.drop_table('raw_material')
    op.drop_table('production_entry')
    op.drop_table('machine_queue')
    op.drop_table('machine_mold')
    op.drop_table('machine')
    op.drop_table('color')
    ### end Alembic commands ###
